language: java
jdk:
  - oraclejdk8

sudo: false

install: true

script:
  - pwd
  - cd webapp
  - mvn install -DskipTests=true
  
after_success:
  - pwd
  - ls -al
  - cd ..
  - ls -al
  - cp infrastructure/aws/codedeploy/*.sh .
  - cp infrastructure/aws/codedeploy/*.yml .
  - zip -r csye6225-web-app-${TRAVIS_JOB_NUMBER}.zip ./webapp/target/ROOT-1.war *.sh *.yml
  - ls -al
  - pwd
  - mkdir codedeploy_artifact
  - mv csye6225-web-app-${TRAVIS_JOB_NUMBER}.zip codedeploy_artifact
  - cd codedeploy_artifact
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al

deploy:
  - provider: s3
    local_dir: codedeploy_artifact
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    on:
      branch: assignment9


  - provider: codedeploy
    access_key_id: $access_key_id
    bucket: $s3_bucket
    key: csye6225-web-app-${TRAVIS_JOB_NUMBER}.zip
    bundle_type: zip
    application: $application
    deployment_group: $deployment_group
    region: us-east-1
    secret_access_key: $secret_access_key
    wait-until-deployed: true
    on:
      branch: assignment9


