version: 0.0
os: linux

files:             
<<<<<<< HEAD
    - source: ./webapp/target/ROOT-1.war
=======
  - source: ./webapp/target/ROOT-1.war
>>>>>>> 17ab7d6fff12270986c87bec7d4d4eaca191b16e
    destination: /opt/tomcat/webapps

hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
   - location: ./applicationStart.sh
     timeout: 180
     runas: centos
